services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: time_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d time_management -U user" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      DATABASE_URI: "postgresql+psycopg://user:password@pg:5432/time_management"
    ports:
      - "80:80"
    depends_on:
      pg:
        condition: service_healthy

volumes:
  pg_data: