[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"
flask-migrate = "^4.0.7"
psycopg = {extras = ["binary", "pool"], version = "^3.2.1"}
flask-pydantic = "^0.12.0"
